version: '3.9'

services:
  postgres:
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_DB=${POSTGRES_DB:-florestario}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - .docker/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge